
----------------------- Tại chi nhánh 1 (user: GIAMDOC) ------------------------
/*tìm tất cả sản phẩm ở CN3 thuộc thuộc danh mục "Điện thoại" đã bán được trên 1000 sản phẩm 
Kết quả thu được: SANPHAM_ID, TENSANPHAM, DANHMUC, THUONGHIEU, XUATXU, GIABAN, SOLUONGBAN*/
SELECT
    SP.SANPHAM_ID,
    SP.TENSANPHAM,
	SP.DANHMUC,
	SP.THUONGHIEU,
	SP.XUATXU,
	SP.GIABAN,
	SUM(CT.SOLUONG) AS SOLUONGBAN
FROM CN3.SANPHAM@CN3_GD_LINK SP
	, CN3.CTHD@CN3_GD_LINK CT
WHERE SP.SANPHAM_ID = CT.SANPHAM_ID
AND SP.DANHMUC = 'Điện thoại'
HAVING SUM(CT.SOLUONG) > 1000
GROUP BY SP.SANPHAM_ID, SP.TENSANPHAM, SP.DANHMUC, SP.THUONGHIEU, SP.XUATXU, SP.GIABAN
ORDER BY SP.SANPHAM_ID;



/*Cho biết doanh thu của cả 3 chi nhánh trong tháng 12/2024
kết quả thu được: CHINHANH_ID, TENCHINHANH, DIACHI, DOANHTHU*/
EXPLAIN PLAN FOR
SELECT 
    CN.CHINHANH_ID,
	CN.TENCHINHANH,
	CN.DIACHI,
	SUM(HD.TONGTIEN) AS DOANHTHU
FROM CN1.HOADON HD 
    CROSS JOIN CN1.CHINHANH CN
WHERE EXTRACT(MONTH FROM HD.NGAYTAO) = 12
  AND EXTRACT(YEAR FROM HD.NGAYTAO) = 2024
GROUP BY CN.CHINHANH_ID, CN.TENCHINHANH, CN.DIACHI
UNION 
SELECT 
    CN2.CHINHANH_ID,
	CN2.TENCHINHANH,
	CN2.DIACHI,
	SUM(HD2.TONGTIEN) AS DOANHTHU
FROM CN2.HOADON@CN2_GD_LINK HD2 
    CROSS JOIN CN2.CHINHANH@CN2_GD_LINK CN2
WHERE EXTRACT(MONTH FROM HD2.NGAYTAO) = 12
  AND EXTRACT(YEAR FROM HD2.NGAYTAO) = 2024
GROUP BY CN2.CHINHANH_ID, CN2.TENCHINHANH, CN2.DIACHI
UNION
SELECT 
    CN3.CHINHANH_ID,
	CN3.TENCHINHANH,
	CN3.DIACHI,
	SUM(HD3.TONGTIEN) AS DOANHTHU
FROM CN3.HOADON@CN3_GD_LINK HD3 
    CROSS JOIN CN3.CHINHANH@CN3_GD_LINK CN3
WHERE EXTRACT(MONTH FROM HD3.NGAYTAO) = 12
  AND EXTRACT(YEAR FROM HD3.NGAYTAO) = 2024
GROUP BY CN3.CHINHANH_ID, CN3.TENCHINHANH, CN3.DIACHI;


/*Cho biết TOP 5 sản phẩm thuộc mỗi danh mục bán chạy nhất ở mỗi chi nhánh
Kết quả thu được: CHINHANH_ID, DANHMUC, SANPHAM_ID, TENSANPHAM, SOLUONGBAN, RANKING*/
SELECT *
FROM (
    SELECT
        CN.CHINHANH_ID,
        SP.DANHMUC,
        SP.SANPHAM_ID,
        SP.TENSANPHAM,
        SUM(CT.SOLUONG) AS SOLUONGBAN,
        ROW_NUMBER() OVER (PARTITION BY CN.CHINHANH_ID, SP.DANHMUC ORDER BY SUM(CT.SOLUONG) DESC) AS RANKING
    FROM CN1.SANPHAM SP
    JOIN CN1.CTHD CT ON CT.SANPHAM_ID = SP.SANPHAM_ID
    JOIN CN1.HOADON HD ON CT.HOADON_ID = HD.HOADON_ID
    CROSS JOIN CN1.CHINHANH CN
    GROUP BY CN.CHINHANH_ID, SP.DANHMUC, SP.SANPHAM_ID, SP.TENSANPHAM
    UNION
    SELECT
        CN.CHINHANH_ID,
        SP.DANHMUC,
        SP.SANPHAM_ID,
        SP.TENSANPHAM,
        SUM(CT.SOLUONG) AS SOLUONGBAN,
        ROW_NUMBER() OVER (PARTITION BY CN.CHINHANH_ID, SP.DANHMUC ORDER BY SUM(CT.SOLUONG) DESC) AS RANKING
    FROM CN2.SANPHAM@CN2_GD_LINK SP
    JOIN CN2.CTHD@CN2_GD_LINK CT ON CT.SANPHAM_ID = SP.SANPHAM_ID
    JOIN CN2.HOADON@CN2_GD_LINK HD ON CT.HOADON_ID = HD.HOADON_ID
    CROSS JOIN CN2.CHINHANH@CN2_GD_LINK CN
    GROUP BY CN.CHINHANH_ID, SP.DANHMUC, SP.SANPHAM_ID, SP.TENSANPHAM
    UNION
    SELECT
        CN.CHINHANH_ID,
        SP.DANHMUC,
        SP.SANPHAM_ID,
        SP.TENSANPHAM,
        SUM(CT.SOLUONG) AS SOLUONGBAN,
        ROW_NUMBER() OVER (PARTITION BY CN.CHINHANH_ID, SP.DANHMUC ORDER BY SUM(CT.SOLUONG) DESC) AS RANKING
    FROM CN3.SANPHAM@CN3_GD_LINK SP
    JOIN CN3.CTHD@CN3_GD_LINK CT ON CT.SANPHAM_ID = SP.SANPHAM_ID
    JOIN CN3.HOADON@CN3_GD_LINK HD ON CT.HOADON_ID = HD.HOADON_ID
    CROSS JOIN CN3.CHINHANH@CN3_GD_LINK CN
    GROUP BY CN.CHINHANH_ID, SP.DANHMUC, SP.SANPHAM_ID, SP.TENSANPHAM
)
WHERE RANKING <= 5
ORDER BY CHINHANH_ID, DANHMUC, RANKING;


/* Cho biết số tuổi trung bình của các nhân viên mỗi chi nhánh 
kết quả thu được: CHINHANH_ID, TENCHINHANH, TUOI_TRUNGBINH*/
SELECT 
    CN.CHINHANH_ID,
    CN.TENCHINHANH,
    ROUND(AVG(MONTHS_BETWEEN(SYSDATE, NV.NGAYSINH) / 12), 1) AS TUOI_TRUNGBINH
FROM CN1.CHINHANH CN
    JOIN CN1.NHANVIEN NV ON NV.CHINHANH_ID = CN.CHINHANH_ID
GROUP BY CN.CHINHANH_ID, CN.TENCHINHANH
UNION 
SELECT 
    CN.CHINHANH_ID,
    CN.TENCHINHANH,
    ROUND(AVG(MONTHS_BETWEEN(SYSDATE, NV.NGAYSINH) / 12), 1) AS TUOI_TRUNGBINH
FROM CN2.CHINHANH@CN2_GD_LINK CN
    JOIN CN2.NHANVIEN@CN2_GD_LINK NV ON NV.CHINHANH_ID = CN.CHINHANH_ID
GROUP BY CN.CHINHANH_ID, CN.TENCHINHANH
UNION
SELECT 
    CN.CHINHANH_ID,
    CN.TENCHINHANH,
    ROUND(AVG(MONTHS_BETWEEN(SYSDATE, NV.NGAYSINH) / 12), 1) AS TUOI_TRUNGBINH
FROM CN3.CHINHANH@CN3_GD_LINK CN
    JOIN CN3.NHANVIEN@CN3_GD_LINK NV ON NV.CHINHANH_ID = CN.CHINHANH_ID
GROUP BY CN.CHINHANH_ID, CN.TENCHINHANH;


/* Tìm những sản phẩm chưa từng được bán ra ở bất kỳ chi nhánh nào
Kết quả trả về: SANPHAM_ID, TENSANPHAM, DANHMUC, THUONGHIEU, XUATXU, GIABAN*/
SELECT 
    SP.SANPHAM_ID, 
    SP.TENSANPHAM,
    SP.DANHMUC,
    SP.THUONGHIEU,
    SP.XUATXU,
    SP.GIABAN
FROM CN1.SANPHAM SP
WHERE SP.SANPHAM_ID NOT IN (
    SELECT DISTINCT SANPHAM_ID FROM CN1.CTHD
    UNION
    SELECT DISTINCT SANPHAM_ID FROM CN2.CTHD@CN2_GD_LINK
    UNION
    SELECT DISTINCT SANPHAM_ID FROM CN3.CTHD@CN3_GD_LINK
);

SELECT 
    SP.SANPHAM_ID, 
    SP.TENSANPHAM,
    SP.DANHMUC,
    SP.THUONGHIEU,
    SP.XUATXU,
    SP.GIABAN
FROM CN1.SANPHAM SP
WHERE NOT EXISTS (
    SELECT 1
    FROM (
        SELECT SANPHAM_ID FROM CN1.CTHD
        UNION
        SELECT SANPHAM_ID FROM CN2.CTHD@CN2_GD_LINK
        UNION
        SELECT SANPHAM_ID FROM CN3.CTHD@CN3_GD_LINK
    ) BANSANPHAM
    WHERE BANSANPHAM.SANPHAM_ID = SP.SANPHAM_ID
);



------------------------- Tại chi nhánh 2 (user: NVBH) -------------------------
/*tìm khách hàng đã khách hàng đã mua 'HP Tai nghe Foreign105' ở cả CN1 VÀ CN2*/
SELECT 
    K2.HOTEN, 
    K2.GIOITINH, 
    K2.NGAYSINH,
    K2.DIACHI, 
    K2.SDT
FROM CN2.KHACHHANG K2
JOIN CN2.HOADON HD2 ON K2.KHACHHANG_ID = HD2.KHACHHANG_ID
JOIN CN2.CTHD CT2 ON HD2.HOADON_ID = CT2.HOADON_ID
JOIN CN2.SANPHAM SP2 ON CT2.SANPHAM_ID = SP2.SANPHAM_ID
WHERE SP2.TENSANPHAM = 'HP Tai nghe Foreign105'
INTERSECT
SELECT  
    K1.HOTEN, 
    K1.GIOITINH, 
    K1.NGAYSINH,
    K1.DIACHI, 
    K1.SDT
FROM CN1.KHACHHANG@CN1_NVBH_LINK K1
JOIN CN1.HOADON@CN1_NVBH_LINK HD1 ON K1.KHACHHANG_ID = HD1.KHACHHANG_ID
JOIN CN1.CTHD@CN1_NVBH_LINK CT1 ON HD1.HOADON_ID = CT1.HOADON_ID
JOIN CN1.SANPHAM@CN1_NVBH_LINK SP1 ON CT1.SANPHAM_ID = SP1.SANPHAM_ID
WHERE SP1.TENSANPHAM = 'HP Tai nghe Foreign105';


/*Tìm khách hàng những khách hàng đã mua cùng lúc từ 3 sản phẩm khác nhau trở lên trong 1 hóa đơn ở CN2
Kết quả trả về: HOADON_ID, KHACHHANG_ID, HOTEN, GIOITINH, NGAYSINH, SO_SANPHAM*/
SELECT 
    HD.HOADON_ID,
    KH.KHACHHANG_ID,
    KH.HOTEN,
    KH.GIOITINH,
    KH.NGAYSINH,
    COUNT(DISTINCT CT.SANPHAM_ID) AS SO_SANPHAM
FROM CN1.KHACHHANG@CN1_NVBH_LINK KH
    JOIN CN1.HOADON@CN1_NVBH_LINK HD ON KH.KHACHHANG_ID = HD.KHACHHANG_ID
    JOIN CN1.CTHD@CN1_NVBH_LINK CT ON HD.HOADON_ID = CT.HOADON_ID
GROUP BY HD.HOADON_ID, KH.KHACHHANG_ID, KH.HOTEN, KH.GIOITINH, KH.NGAYSINH
HAVING COUNT(DISTINCT CT.SANPHAM_ID) = 3
ORDER BY SO_SANPHAM;


------------------------ Tại chi nhánh 3 (user: NVKHO) -------------------------
/*Cho biết những sản phẩm chỉ có ở kho CN1 nhưng không có ở CN2, CN3 
kết quả thu được: SANPHAM_ID, TENSANPHAM, DANHMUC, THUONGHIEU, XUATXU, GIABAN*/
SELECT 
    SP.SANPHAM_ID,
    SP.TENSANPHAM,
    SP.DANHMUC,
    SP.THUONGHIEU,
    SP.XUATXU,
    SP.GIABAN
FROM CN1.SANPHAM@CN1_NVKHO_LINK SP
    , CN1.KHOSANPHAM_QLKHO@CN1_NVKHO_LINK KHO
WHERE SP.SANPHAM_ID = KHO.SANPHAM_ID
MINUS
SELECT 
    SP2.SANPHAM_ID,
    SP2.TENSANPHAM,
    SP2.DANHMUC,
    SP2.THUONGHIEU,
    SP2.XUATXU,
    SP2.GIABAN
FROM CN2.SANPHAM@CN2_NVKHO_LINK SP2
    , CN2.KHOSANPHAM_QLKHO@CN2_NVKHO_LINK KHO2
WHERE SP2.SANPHAM_ID = KHO2.SANPHAM_ID
MINUS
SELECT 
    SP3.SANPHAM_ID,
    SP3.TENSANPHAM,
    SP3.DANHMUC,
    SP3.THUONGHIEU,
    SP3.XUATXU,
    SP3.GIABAN
FROM CN3.SANPHAM SP3
    , CN3.KHOSANPHAM_QLKHO KHO3
WHERE SP3.SANPHAM_ID = KHO3.SANPHAM_ID
ORDER BY SANPHAM_ID;


/*cho biết những sản phẩm có mặt ở mọi kho trong 3 chi nhánh 
Kết quả thu được: SANPHAM_ID, TENSANPHAM, DANHMUC, THUONGHIEU, XUATXU, GIABAN*/
SELECT 
    SP.SANPHAM_ID,
    SP.TENSANPHAM,
    SP.DANHMUC,
    SP.THUONGHIEU,
    SP.XUATXU,
    SP.GIABAN
FROM CN3.SANPHAM SP
WHERE SP.SANPHAM_ID IN (
    SELECT SANPHAM_ID
    FROM (
        SELECT SANPHAM_ID, 'CN1' AS CN FROM CN1.KHOSANPHAM_QLKHO@CN1_NVKHO_LINK
        UNION ALL
        SELECT SANPHAM_ID, 'CN2' AS CN FROM CN2.KHOSANPHAM_QLKHO@CN2_NVKHO_LINK
        UNION ALL
        SELECT SANPHAM_ID, 'CN3' AS CN FROM CN3.KHOSANPHAM_QLKHO
    )
    GROUP BY SANPHAM_ID
    HAVING COUNT(DISTINCT CN) = 3
);


/*Tìm sản phẩm có số lượng hàng tồn trong kho bé hơn 10 ở cả 3 chi nhánh 
Kết quả thu được: SANPHAM_ID, TENSANPHAM, DANHMUC, THUONGHIEU, SOLUONGNHAP*/
SELECT 
    SP.SANPHAM_ID, 
    SP.TENSANPHAM,
    SP.DANHMUC,
    SP.THUONGHIEU,
    KHO.SOLUONGNHAP   
FROM CN1.SANPHAM@CN1_NVKHO_LINK SP
    INNER JOIN CN1.KHOSANPHAM_QLKHO@CN1_NVKHO_LINK KHO
    ON SP.SANPHAM_ID = KHO.SANPHAM_ID
WHERE KHO.SOLUONGNHAP < 10
UNION
SELECT 
    SP.SANPHAM_ID, 
    SP.TENSANPHAM,
    SP.DANHMUC,
    SP.THUONGHIEU,
    KHO.SOLUONGNHAP   
FROM CN2.SANPHAM@CN2_NVKHO_LINK SP
    INNER JOIN CN2.KHOSANPHAM_QLKHO@CN2_NVKHO_LINK KHO
    ON SP.SANPHAM_ID = KHO.SANPHAM_ID
WHERE KHO.SOLUONGNHAP < 10
UNION
SELECT 
    SP.SANPHAM_ID, 
    SP.TENSANPHAM,
    SP.DANHMUC,
    SP.THUONGHIEU,
    KHO.SOLUONGNHAP   
FROM CN3.SANPHAM SP
    INNER JOIN CN3.KHOSANPHAM_QLKHO KHO
    ON SP.SANPHAM_ID = KHO.SANPHAM_ID
WHERE KHO.SOLUONGNHAP < 10
ORDER BY 5 DESC ;


























































