CREATE TABLE CHINHANH(
CHINHANH_ID VARCHAR2(5) CONSTRAINT PK_CHINHANH PRIMARY KEY,
TENCHINHANH VARCHAR2(200),
DIACHI VARCHAR2(200)
);

CREATE TABLE NHANVIEN(
NHANVIEN_ID NUMBER
CONSTRAINT PK_NHANVIEN PRIMARY KEY,
HOTEN VARCHAR2(250),
GIOITINH VARCHAR(10),
NGAYSINH DATE,
DIACHI VARCHAR2(200),
SDT VARCHAR2(200),
NGAYVAOLAM DATE,
CHUCVU VARCHAR2(200),
LUONG NUMBER,
CHINHANH_ID VARCHAR2(5),
CONSTRAINT FK_NHANVIEN_CHINHANH FOREIGN KEY(CHINHANH_ID) REFERENCES CHINHANH (CHINHANH_ID)
);

CREATE TABLE KHACHHANG(
KHACHHANG_ID NUMBER CONSTRAINT PK_KHACHHANG PRIMARY KEY,
HOTEN VARCHAR2(250),
GIOITINH VARCHAR(10),
NGAYSINH DATE,
SDT VARCHAR2(200),
DIACHI VARCHAR2(200),
NGAYDANGKY DATE,
TONGTIENTHANHTOAN NUMBER);


CREATE TABLE SANPHAM(
SANPHAM_ID NUMBER CONSTRAINT PK_SANPHAM PRIMARY KEY,
TENSANPHAM VARCHAR2(200),
DANHMUC VARCHAR2(200),
THUONGHIEU VARCHAR2(200),
XUATXU VARCHAR2(200),
GIANHAP NUMBER,
GIABAN NUMBER,
NGAYSANXUAT DATE,
TGBAOHANH NUMBER
);

CREATE TABLE KHOSANPHAM_QLKHO (
CHINHANH_ID VARCHAR2(5),
SANPHAM_ID NUMBER,
SOLUONGNHAP NUMBER,
NGAYCAPNHAT DATE,
CONSTRAINT PK_QLKHO PRIMARY KEY (CHINHANH_ID, SANPHAM_ID),
CONSTRAINT FK_QLKHO_CHINHANH FOREIGN KEY (CHINHANH_ID) REFERENCES CHINHANH (CHINHANH_ID),
CONSTRAINT FK_QLKHO_SANPHAM FOREIGN KEY (SANPHAM_ID) REFERENCES SANPHAM (SANPHAM_ID)
);

CREATE TABLE KHOSANPHAM_QLBANHANG(
CHINHANH_ID VARCHAR2(5),
SANPHAM_ID NUMBER,
TINHTRANG VARCHAR2(200),
CONSTRAINT PK_QLBANHANG PRIMARY KEY (CHINHANH_ID, SANPHAM_ID),
CONSTRAINT FK_QLBANHANG_CHINHANH FOREIGN KEY (CHINHANH_ID) REFERENCES CHINHANH (CHINHANH_ID),
CONSTRAINT FK_QLBANHANG_SANPHAM FOREIGN KEY (SANPHAM_ID) REFERENCES SANPHAM (SANPHAM_ID)
);

CREATE TABLE HOADON(
HOADON_ID NUMBER CONSTRAINT
PK_HOADON PRIMARY KEY,
NHANVIEN_ID NUMBER,
KHACHHANG_ID NUMBER,
NGAYTAO DATE,
TONGTIEN NUMBER,
CONSTRAINT FK_HOADON_NHANVIEN FOREIGN KEY (NHANVIEN_ID) REFERENCES NHANVIEN (NHANVIEN_ID),
CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (KHACHHANG_ID) REFERENCES KHACHHANG (KHACHHANG_ID)
);

CREATE TABLE CTHD(
HOADON_ID NUMBER,
SANPHAM_ID NUMBER,
SOLUONG INT,
CONSTRAINT PK_CTHD PRIMARY KEY (HOADON_ID, SANPHAM_ID),
CONSTRAINT FK_CTHD_HOADON FOREIGN KEY (HOADON_ID) REFERENCES HOADON (HOADON_ID),
CONSTRAINT FK_CTHD_SANPHAM FOREIGN KEY (SANPHAM_ID) REFERENCES SANPHAM (SANPHAM_ID)
);

