-- truy vấn cục bộ ban đầu
EXPLAIN PLAN FOR
SET TIMING ON;
SELECT DISTINCT NV.HOTEN, HD.HOADON_ID, HD.NGAYTAO, HD.TONGTIEN
FROM 
    (SELECT * FROM CN1.CHINHANH
    UNION ALL
     SELECT * FROM CN2.CHINHANH@CN2_GD_LINK
    UNION ALL
     SELECT * FROM CN3.CHINHANH@CN3_GD_LINK) CN, 
    (SELECT * FROM CN1.NHANVIEN
    UNION ALL
     SELECT * FROM CN2.NHANVIEN@CN2_GD_LINK
    UNION ALL
     SELECT * FROM CN3.NHANVIEN@CN3_GD_LINK) NV, 
    (SELECT * FROM CN1.KHACHHANG
    UNION ALL
     SELECT * FROM CN2.KHACHHANG@CN2_GD_LINK
    UNION ALL
     SELECT * FROM CN3.KHACHHANG@CN3_GD_LINK) KH, 
    (SELECT * FROM CN1.HOADON
    UNION ALL
     SELECT * FROM CN2.HOADON@CN2_GD_LINK
    UNION ALL
     SELECT * FROM CN3.HOADON@CN3_GD_LINK) HD, 
    (SELECT * FROM CN1.CTHD
    UNION ALL
     SELECT * FROM CN2.CTHD@CN2_GD_LINK
    UNION ALL
     SELECT * FROM CN3.CTHD@CN3_GD_LINK) CT, 
    (SELECT * FROM CN1.SANPHAM
    UNION ALL
     SELECT * FROM CN2.SANPHAM@CN2_GD_LINK
    UNION ALL
     SELECT * FROM CN3.SANPHAM@CN3_GD_LINK) SP
WHERE NV.CHINHANH_ID = CN.CHINHANH_ID AND HD.NHANVIEN_ID = NV.NHANVIEN_ID
  AND HD.KHACHHANG_ID = KH.KHACHHANG_ID AND HD.HOADON_ID = CT.HOADON_ID
  AND CT.SANPHAM_ID = SP.SANPHAM_ID AND CN.TENCHINHANH = 'Chi nhánh Quận 1'
  AND KH.HOTEN = 'Phan Văn Dũng' AND SP.THUONGHIEU = 'Xiaomi'
  AND CT.SOLUONG = 3;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);



-- Truy vấn tối ưu
EXPLAIN PLAN FOR
SET TIMING ON;
SELECT DISTINCT D.HOTEN, D.HOADON_ID, D.NGAYTAO, D.TONGTIEN
FROM (
        SELECT HOADON_ID
        FROM (
                SELECT SANPHAM_ID FROM CN1.SANPHAM WHERE THUONGHIEU = 'Xiaomi'
                UNION ALL
                SELECT SANPHAM_ID FROM CN2.SANPHAM@CN2_GD_LINK WHERE THUONGHIEU = 'Xiaomi'
                UNION ALL
                SELECT SANPHAM_ID FROM CN3.SANPHAM@CN3_GD_LINK WHERE THUONGHIEU = 'Xiaomi'
            ) SP
        JOIN 
            (
                SELECT HOADON_ID, SANPHAM_ID FROM CN1.CTHD WHERE SOLUONG = 3
                UNION ALL
                SELECT HOADON_ID, SANPHAM_ID FROM CN2.CTHD@CN2_GD_LINK WHERE SOLUONG = 3
                UNION ALL
                SELECT HOADON_ID, SANPHAM_ID FROM CN3.CTHD@CN3_GD_LINK WHERE SOLUONG = 3
            ) CT
        ON SP.SANPHAM_ID = CT.SANPHAM_ID
    ) A
JOIN 
    (
        SELECT B.HOADON_ID, C.NHANVIEN_ID, B.NGAYTAO, B.TONGTIEN, C.HOTEN
        FROM(
            SELECT HOADON_ID, NHANVIEN_ID, NGAYTAO, TONGTIEN
            FROM (
                    SELECT HOADON_ID, NHANVIEN_ID, NGAYTAO, TONGTIEN, KHACHHANG_ID FROM CN1.HOADON
                    UNION ALL
                    SELECT HOADON_ID, NHANVIEN_ID, NGAYTAO, TONGTIEN, KHACHHANG_ID FROM CN2.HOADON@CN2_GD_LINK
                    UNION ALL
                    SELECT HOADON_ID, NHANVIEN_ID, NGAYTAO, TONGTIEN, KHACHHANG_ID FROM CN3.HOADON@CN3_GD_LINK
                ) HD
            JOIN 
                (
                    SELECT KHACHHANG_ID FROM CN1.KHACHHANG WHERE HOTEN = 'Phan Văn Dũng'
                    UNION ALL
                    SELECT KHACHHANG_ID FROM CN2.KHACHHANG@CN2_GD_LINK WHERE HOTEN = 'Phan Văn Dũng'
                    UNION ALL
                    SELECT KHACHHANG_ID FROM CN3.KHACHHANG@CN3_GD_LINK WHERE HOTEN = 'Phan Văn Dũng'
                ) KH ON HD.KHACHHANG_ID = KH.KHACHHANG_ID
            ) B 
        JOIN 
            (
                SELECT NV.NHANVIEN_ID, NV.HOTEN
                FROM (
                        SELECT NHANVIEN_ID, CHINHANH_ID, HOTEN FROM CN1.NHANVIEN
                        UNION ALL
                        SELECT NHANVIEN_ID, CHINHANH_ID, HOTEN FROM CN2.NHANVIEN@CN2_GD_LINK
                        UNION ALL
                        SELECT NHANVIEN_ID, CHINHANH_ID, HOTEN FROM CN3.NHANVIEN@CN3_GD_LINK
                    ) NV
                JOIN 
                    (
                        SELECT CHINHANH_ID FROM CN1.CHINHANH WHERE TENCHINHANH = 'Chi nhánh Quận 1'
                        UNION ALL
                        SELECT CHINHANH_ID FROM CN2.CHINHANH@CN2_GD_LINK WHERE TENCHINHANH = 'Chi nhánh Quận 1'
                        UNION ALL
                        SELECT CHINHANH_ID FROM CN3.CHINHANH@CN3_GD_LINK WHERE TENCHINHANH = 'Chi nhánh Quận 1'
                    ) CN 
                ON NV.CHINHANH_ID = CN.CHINHANH_ID
            ) C 
        ON C.NHANVIEN_ID = B.NHANVIEN_ID
    ) D
ON D.HOADON_ID = A.HOADON_ID;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);



-- tối ưu trên từng phân mảnh
EXPLAIN PLAN FOR
SELECT DISTINCT H.HOTEN, H.HOADON_ID, H.NGAYTAO, H.TONGTIEN
FROM 
(SELECT HOADON_ID
        FROM (SELECT SANPHAM_ID FROM CN1.SANPHAM WHERE THUONGHIEU = 'Xiaomi') A
            JOIN
             (SELECT HOADON_ID, SANPHAM_ID FROM CN1.CTHD WHERE SOLUONG = 3) B
            ON A.SANPHAM_ID = B.SANPHAM_ID) C
JOIN
(SELECT HOTEN, HOADON_ID, NGAYTAO, TONGTIEN
        FROM (SELECT NHANVIEN_ID, HOADON_ID, NGAYTAO, TONGTIEN
                FROM (SELECT KHACHHANG_ID, NHANVIEN_ID, HOADON_ID, NGAYTAO, TONGTIEN FROM CN1.HOADON) D
                    JOIN
                     (SELECT KHACHHANG_ID FROM CN1.KHACHHANG WHERE HOTEN = 'Phan Văn Dũng') E
                    ON D.KHACHHANG_ID = E.KHACHHANG_ID) F
            JOIN
             (SELECT NHANVIEN_ID, HOTEN FROM CN1.NHANVIEN) G
            ON F.NHANVIEN_ID = G.NHANVIEN_ID) H
ON C.HOADON_ID = H.HOADON_ID;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);














